### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/social#20]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [x] mail_optional_autofollow - By @lmignon - #62
- [x] email_template_qweb - By @lasley - #57
- [ ] mail_as_letter
- [x] mail_attach_existing_attachment - By @sergio-teruel - #68
- [x] mail_debrand - By @darshan-serpent - #155 
- [ ] mail_full_expand
- [x] mass_mailing_custom_unsubscribe
- [x] mail_compose_select_lang
- [ ] mail_restrict_follower_selection
- [ ] mail_follower_custom_notification
- [ ] mail_footer_notified_partners
- [ ] mail_forward
- [x] mail_full_expand
- [ ] mail_mandrill
- [x] mail_optional_autofollow
- [ ] mail_read_new_window
- [x] mail_restrict_follower_selection
- [ ] mail_sent
- [x] mail_tracking
- [x] mail_tracking_mailgun
- [x] mail_tracking_mass_mailing - By @cubells - #144 
- [x] marketing_security_group > mass_mailing_security_group - By @cubells - #128 
- [ ] mass_mailing_custom_unsubscribe
- [ ] mass_mailing_statistic_extra
- [x] mass_mailing_unique - By @cubells - #136 
- [ ] portal_welcome_email_template - By @nicomacr - #134 
- [ ] social_media_dribbble
- [ ] social_media_tripadvisor
- [ ] social_media_xing
- [ ] website_mail_snippet_bg_color > web_editor_background_color - By @yajo https://github.com/OCA/web/pull/582
- [ ] website_mail_snippet_table_edit

**Comment by stephankeller** [comment]
We are porting mail_attach_existing_attachment to V9.

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by rafaelbn** [comment]
Hi, I think there are some modules here missing to migrate, isn't it?

**Comment by pedrobaeza** [comment]
That's because they were developed after the creation of the branch. Feel free to add them here.
