### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/social#203]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] base_search_mail_content - By @cubells - #282 
- [x] email_template_qweb - By @celm1990 - #250  
- [x] fetchmail_thread_default - By @chienandalu - #339
- [ ] mail_as_letter
- [x] mail_attach_existing_attachment - By @ernestotejeda - #260 
- [ ] mail_compose_select_lang
- [x] mail_debrand - By @lreficent - #265 
- [x] mail_digest - By @simahawk - #225 
- [ ] mail_footer_notified_partner - By @invitu - #289 
- [ ] mail_full_expand
- [ ] mail_improved_tracking_value - By @mpanarin - #254
- [ ] mail_notify_bounce
- [x] mail_optional_autofollow - By @damcar - #212 
- [ ] mail_optional_follower_notification
- [x] mail_restrict_follower_selection - By @phucngta - #239 
- [x] mail_tracking - By @chienandalu - #244 
- [x] mail_tracking_mailgun - By @chienandalu - #268 
- [x] mail_tracking_mass_mailing - By @pedrobaeza -  #293 
- [ ] mail_sendgrid - By @Nooka10 - #486
- [x] mass_mailing_custom_unsubscribe - By @chienandalu - #279 
- [ ] mass_mailing_event - By @thinkwelltwd - https://github.com/OCA/social/pull/367
- [ ] mass_mailing_list_dynamic - By @damcar - #284
- [x] mass_mailing_partner - By @ernestotejeda - #277 
- [x] mass_mailing_resend - By @pedrobaeza - #294 
- [x] mass_mailing_unique - By @ernestotejeda - #276 
- [ ] website_mass_mailing_name

**Comment by celm1990** [comment]
email_template_qweb PR #249

**Comment by LoisRForgeFlow** [comment]
mail_debrand https://github.com/OCA/social/pull/265

**Comment by emagdalenaC2i** [comment]
@pedrobaeza 
mail_digest #225 is done

**Comment by cvinh** [comment]
@pedrobaeza could you add mail_footer_notified_partner in todo list ? I tested 10.0 branch towards odoo v11 , it works out of the box
I'm pushing a PR
thanks

**Comment by pedrobaeza** [comment]
OK, @invitu, I'll fill all the info when you make the PR.

**Comment by dajuayen** [comment]
Regarding "mail_optional_follower_notification", @pedrobaeza, we have a development done in version 11 so that by default the checkBox is not marked when sending messages.
![checkboxoff](https://user-images.githubusercontent.com/3779635/43045702-b10053fc-8dbd-11e8-8ba4-9f6b0d1cec85.png)
The question is to unmark the following checkbox?
![invite_follower](https://user-images.githubusercontent.com/3779635/43045726-452618dc-8dbe-11e8-98a3-cd67e4b2a014.png)
If so, I think we can do it.

**Comment by pedrobaeza** [comment]
@Dajuayen I think that already exists. @lmignon can you assist me to say it firmly? I think you or one of your team did it.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, add to the list fetchmail_thread_default - By @chienandalu - #339 

Please, add to the list mass_mailing_list_dynamic - By @damcar - #284 

Please, add to the list mail_improved_tracking_value - By @mpanarin - #254

**Comment by ecino** [comment]
@pedrobaeza mail_sendgrid - By @Nooka10 - #486

**Comment by pedrobaeza** [comment]
@ecino I'm not anymore as OCA's community manager, so I'm not handling this now. I have proposed https://github.com/OCA/oca-github-bot/pull/97 for a way to maintain easily the migration issues.

**Comment by renzo1974** [comment]
Is there a reason why the module **mail_notify_bounce** is not listed for migration?

**Comment by harlibeub** [comment]
> Is there a reason why the module **mail_notify_bounce** is not listed for migration?

ye.. good question... and no feedback.. as usal

**Comment by simahawk** [comment]
@harlibeub you can candidate yourself to be a member of PSC in this repo and provide prompt answers to such questions :wink: 
To do so, you should just spend some time in reviewing and contributing to this repo.
Anybody can do it.

Also, you could help to finish this https://github.com/OCA/oca-github-bot/pull/97.
Would be very appreciated.

@rm-jamotion I added it.

**Comment by rafaelbn** [comment]
Updated:

- [ ] mass_mailing_event - By @thinkwelltwd - https://github.com/OCA/social/pull/367
