### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/social#95]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] base_search_mail_content - By @mreficent - #180 
- [x] email_template_qweb - By @dbo-odoo - #98 
- [x] mail_as_letter - By @dbo-odoo - #100
- [x] mail_attach_existing_attachment - By @dbo-odoo - #99 
- [ ] mail_compose_select_lang - By @dbo-odoo - #101 
- [x] mail_debrand - By @pedrobaeza - #168 
- [x] mail_digest - By @simahawk - #187 
- [x] mail_footer_notified_partners - By @SimoRubi - #200
- [x] mail_forward - By @ecino - #256 
- [x] mail_full_expand- By @dbo-odoo - #112 
- [x] mail_optional_autofollow- By @dbo-odoo - #109 
- [x] mail_optional_follower_notification - By @adrienpeiffer - #115 
- [x] mail_restrict_follower_selection- By @dbo-odoo - #110 
- [x] mail_tracking - By @dbo-odoo - #108 
- [x] mail_tracking_mailgun - By @dbo-odoo - #111 
- [x] mail_tracking_mass_mailing - By @chienandalu - #174 
- [x] mass_mailing_custom_unsubscribe - By @Yajo - #178 
- [x] mass_mailing_event - By @chienandalu - #173 
- [x] mass_mailing_partner - By @chienandalu - #171 
- [x] mass_mailing_unique - By @pedrobaeza - #188 
- [x] website_mass_mailing_name - By @Yajo - #179

**Comment by bouvyd** [comment]
Hi,

For [Hackotberfest](https://hacktoberfest.digitalocean.com/), I've decided to do something useful and have a look at OCA modules in need of a migration to 10.0. Also, the Odoo Experience reminded me how the community can be motivating at times (which is not apparent if you work in support :stuck_out_tongue: ), so here I am migrating things...

I've done the first four modules in your list (no one manifested itself until now, so I assumed the work had not began yet); depending on time and motivation, I was hoping to sweep the whole repo.

I assume you prefer one PR per module since it allows easier discussion and will not prevent merging if one migration is problematic; if you'd prefer a single big PR don't hesitate to say so!

**Comment by pedrobaeza** [comment]
Damien, thanks for your contribution! It's good to see this kind of initiatives. I'm writing the PRs you have contributed in the issue.

**Comment by bouvyd** [comment]
About `mass_mailing_custom_unsubcribe`, I'm not really sure the module is still needed since the link is easily editable in the template with the mass mailing template editor in v10 (with the added bonus of translation support). I'll leave that one for someone else if anyone wants it :-)

**Comment by lasley** [comment]
You're a beast @dbo-odoo - all modules upgraded to v10 outside of the `mass_mailing_custom_unsubcribe` which I agree now duplicates Odoo core feature-set.

**Comment by pedrobaeza** [comment]
Indeed he has made a real achievement: migrate a full repo!

Does core unsubscribe allow to specify a reason for unsubscribing?

**Comment by pedrobaeza** [comment]
@dbo-odoo Maybe you want to migrate other 8.0 modules that don't get to 9.0 because they were developed after the branch creation, like https://github.com/OCA/social/tree/8.0/mail_tracking_mass_mailing or https://github.com/OCA/social/tree/8.0/mass_mailing_sending_queue? :wink:

**Comment by rafaelbn** [comment]
About https://github.com/OCA/social/issues/95#issuecomment-253913196 @dbo-odoo  `mass_mailing_custom_unsubcribe` there are more functionalities we must take care like Unsubscription Reasons https://github.com/OCA/social/blame/8.0/mass_mailing_custom_unsubscribe/README.rst#L38
If we migrate from v8 to v9 and v10 that info cannot be lost.

**Comment by ecino** [comment]
I have done the migration of `mail_tracking_mass_mailing` in #177

**Comment by abhishekkumaresan** [comment]
Hi, 
Anybody migrating mail_compose_select_lang 
I am trying to migrate it, but I am not able bring the translated template (ie), I click on a language from force_language drop-down,The onchnage_template_id method is  called but the output returned is in the same language(english)


I could not find where I am going wrong,
I  compared the methods in the call stack of this process between odoo8 and odoo9 but still I am able to find only one difference 


```
ctx = context.copy()
if template.lang:
         ctx['lang'] = template._context.get('lang')
```


this is in generate_email_batch method of email_template.py of email_template module in odoo8
``


I am new to odoo development (A fresher with 2 months experience)   
can any one correct me, Pls comment back if I have to commit my code
I am trying to run mail_compose_select_lang with dependency as `'mail' ` module in odoo 9

**Comment by pedrobaeza** [comment]
You can see in https://github.com/OCA/social/pull/101 the reasons why it's not easily done, but anyway that part seems to be done there.

**Comment by abhishekkumaresan** [comment]
@pedrobaeza Thank You

**Comment by SimoRubi** [comment]
Hi,
I'm working on the migration of module mail_footer_notified_partners

**Comment by pedrobaeza** [comment]
OK, noted in the main comment. As per OCA policy (https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#modules), better to stick to singular names, so I suggest you to rename to mail_show_notified_partner.

**Comment by SimoRubi** [comment]
Sure, I've renamed the module and created the PR #200

**Comment by ecino** [comment]
Added module mail_forward in #256
