### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/social#974]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] base_search_mail_content - By @Highcooley - #1154
- [x] base_user_signature - By @Saran440 - #1365
- [ ] fetchmail_thread_default - By @ntsirintanis - #1329
- [x] mail_activity_board - By @augusto-weiss - #1006
- [ ] mail_activity_creator
- [ ] mail_activity_done - By @ignissak - #1059
- [ ] mail_activity_partner
- [x] mail_activity_plan - By @victoralmau - #1335
- [x] mail_activity_reminder - By @sebalix - #1228
- [ ] mail_activity_team - By @rven - #1129
- [ ] mail_attach_existing_attachment
- [x] mail_attach_existing_attachment - By @baimont - #976
- [x] mail_attach_existing_attachment_account - By @sbidoul - #1508
- [x] mail_autogenerated_header - By @LauraCForgeFlow - #1677
- [x] mail_autosubscribe - By @Vandan-OSI - #1115
- [x] mail_composer_cc_bcc - By @sonhd91 - #1224
- [x] mail_debrand - By @SodexisTeam - #1021
- [x] mail_drop_target - By @nguyenminhchien - #1217
- [x] mail_improved_tracking_value - By @ajaniszewska-dev - #1163
- [x] mail_layout_force - By @Abranes - #1333
- [x] mail_notification_custom_subject - By @edlopen - #1454
- [x] mail_optional_autofollow - By @baimont - #975
- [ ] mail_optional_follower_notification
- [x] mail_outbound_static - By @dreispt - #1035
- [x] mail_post_defer - By @yajo - #1213
- [x] ~~mail_preview_base~~ Included in core
- [x] mail_quoted_reply - By @Borruso - #1165
- [ ] mail_restrict_sale_button - By @SMaciasOSI - #1112
- [ ] mail_send_copy - By @legalsylvain - #1271
- [x] mail_show_follower - By @bosd - #1132
- [x] mail_template_multi_attachment - By @atchuthan - #1094
- [x] mail_tracking - By @payen000 - #1216
- [x] mail_tracking_mailgun - By @chienandalu - #1247
- [x] mail_tracking_mass_mailing - By @chienandalu - #1248
- [x] mass_mailing_custom_unsubscribe - By @carolinafernandez-tecnativa - #1315
- [x] mass_mailing_event_registration_exclude - By @carolinafernandez-tecnativa - #1225
- [x] mass_mailing_list_dynamic - By @nguyenminhchien - #1089
- [x] mass_mailing_partner - By @nguyenminhchien - #1084
- [x] mass_mailing_resend - By @nguyenhk99 - #1100
- [x] mass_mailing_unique - By @ChrisOForgeFlow - #1265

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by augusto-weiss** [comment]
mail_activity_board #1006

**Comment by pegonzalezspesol** [comment]
Working on mail_activity_team

**Comment by dzungtran89** [comment]
- email_template_qweb: https://github.com/OCA/social/pull/1111

**Comment by ignissak** [comment]
mail_activity_done WIP
mail_activity_partner WIP

**Comment by yankinmax** [comment]
mail_optional_follower_notification
- [ ] https://github.com/OCA/social/pull/1071

**Comment by alan196** [comment]
mail_tracking_mailgun in https://github.com/OCA/social/pull/1073

**Comment by nguyenminhchien** [comment]
mass_mailing_partner:  https://github.com/OCA/social/pull/1084
mass_mailing_list_dynamic: https://github.com/OCA/social/pull/1089

**Comment by nguyenhk99** [comment]
mail_tracking_mass_mailing: #1099

**Comment by nguyenhk99** [comment]
mass_mailing_resend: #1100

**Comment by nguyenhk99** [comment]
mail_internal_chat: WIP

**Comment by amkarthik** [comment]
> mail_activity_done WIP

Hi @ignissak 
Do we have any update in migrating the above app?
Planning to migrate this app.
Please let me know if you would like to continue your work on this app.
Thanks

**Comment by ignissak** [comment]
> 
> > mail_activity_done WIP
> 
> Hi @ignissak 
> Do we have any update in migrating the above app?
> Planning to migrate this app.
> Please let me know if you would like to continue your work on this app.
> Thanks
> 

https://github.com/OCA/social/pull/1059

**Comment by odoo-sh** [comment]
> > > mail_activity_done WIP
> > 
> > 
> > Hi @ignissak
> > Do we have any update in migrating the above app?
> > Planning to migrate this app.
> > Please let me know if you would like to continue your work on this app.
> > Thanks
> 
> #1059

@ignissak 
I missed seeing it.
I will review the changes.
Thanks.

**Comment by amkarthik** [comment]
> > > mail_activity_done WIP
> > 
> > 
> > Hi @ignissak
> > Do we have any update in migrating the above app?
> > Planning to migrate this app.
> > Please let me know if you would like to continue your work on this app.
> > Thanks
> 
> #1059
@ignissak 
I missed seeing it.
I will review the changes.
Thanks.

**Comment by sonhd91** [comment]
`mail_inline_css`: https://github.com/OCA/social/pull/1124

**Comment by amkarthik** [comment]
mail_template_substitute: https://github.com/OCA/social/pull/1120

**Comment by rven** [comment]
`mail_activity_team`: https://github.com/OCA/social/pull/1129

**Comment by sonhd91** [comment]
`mail_layout_preview` : https://github.com/OCA/social/pull/1144

**Comment by bosd** [comment]
mail_show_follower #1132

**Comment by bosd** [comment]
mail_activity_creator TEST #1133

**Comment by BT-anieto** [comment]
Missing mail_template_multi_attachment

**Comment by JorgeQuinteros** [comment]
Missing mail_quoted_reply

**Comment by Borruso** [comment]
Migration `mail_quoted_reply` #1165

**Comment by santostelmo** [comment]
Migrating `mail_notification_custom_subject` https://github.com/OCA/social/pull/1171

**Comment by dariodelzozzo** [comment]
https://github.com/OCA/social/pull/1170 mail_activity_partner

**Comment by dariodelzozzo** [comment]
https://github.com/OCA/social/pull/1169 mail_activity_creator

**Comment by llabusch93** [comment]
Completed the migration of PR https://github.com/OCA/social/pull/1165 in this PR to the branch what is in the initial PR https://github.com/Borruso/social/pull/1.

I hope that it alright this way.

**Comment by rpinset** [comment]
Hello mass_mailing_sending_queue is missing (from 14.0)

**Comment by sonhd91** [comment]
`mail_composer_cc_bcc`:  https://github.com/OCA/social/pull/1224

**Comment by CRogos** [comment]
migrating
mass_mailing_subscription_date #1300
mass_mailing_contact_partner #1301
mass_mailing_company_newsletter  #1302

**Comment by antoniospneto** [comment]
mail_contact_type: https://github.com/OCA/social/pull/1617
